# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
      rootFolderOrFile: "$(Build.Repository.LocalPath)"
      includeRootFolder: false
      archiveFile: "$(Build.Repository.LocalPath)/target/helloworld.war"

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
      rootFolderOrFile: "$(Build.Repository.LocalPath)"
      includeRootFolder: false
      archiveFile: "$(Build.Repository.LocalPath)/target/saap.xml"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/helloworld.war'
  name: 'drop'

- task: CmdLine@2
  inputs:
    script: 'curl -X POST   ''http://appsvr4.industrysoln.sl.edst.ibm.com:8004/sap/bc/srt/rfc/sap/zvsts_ci_check/350/zvsts_ci_check1/zvsts_ci_check1''   -H ''authorization: Basic YmNoYXR0ZXJqZWU6aWJtMTIz''   -H ''cache-control: no-cache''   -H ''content-type: text/xml''   -d ''<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:sap-com:document:sap:rfc:functions">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:ZVSTS_CI_CHECK>
         <!--Optional:-->
         <IM_I_EMAIL>
            <!--Zero or more repetitions:-->
            <item></item>
         </IM_I_EMAIL>
         <!--Optional:-->
         <IM_V_OBJECT>ZMMR_MD05_SHORTAGE_REPORT</IM_V_OBJECT>
         <!--Optional:-->
         <IM_V_TRANSPORT></IM_V_TRANSPORT>
      </urn:ZVSTS_CI_CHECK>
   </soapenv:Body>
</soapenv:Envelope>'' > $(System.DefaultWorkingDirectory)/target/saap.xml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/saap.xml'
  name: 'drill'

# Upper code is proper don't touch=========================
- script:
    cd $(System.DefaultWorkingDirectory)
- script:
    ls -l
- script:
    pwd
- script: |
    cd /home/vsts/work/1/s/target
    ls -l
# ==========================================Archive files
# - task: ArchiveFiles@2
#   displayName: "Script Log File"
#   inputs:
#       rootFolderOrFile: "$(Build.Repository.LocalPath)"
#       includeRootFolder: false
#       archiveFile: "$(Build.Repository.LocalPath)/target/test.json"

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/target/test.json'
#   name: 'TestJson'
#=======================================

- script: |
    cd /Users/ibmadmin/Documents/SFWorkspace
    rm -rf /Users/ibmadmin/Documents/SFWorkspace/*
    git clone -b $(Build.SourceBranchName) git@ssh.dev.azure.com:v3/kpatelk2010/PomFri/PomFri

  displayName: "Download/Clone Artifacts"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '#!/bin/sh
      count=1
      result=`cat $(System.DefaultWorkingDirectory)/target/saap.xml | awk -v FS="(<EX_V_RESULT>|</EX_V_RESULT>)" ''{print $2}''`
      echo "Result: $result"
       
      item="$(egrep -o ''</item>'' $(System.DefaultWorkingDirectory)/target/saap.xml  |wc -l)"
       
      json_header=$(echo -e "{     \n
          \"itemTotal\": \"$item\", \n\t
          \"result\": \"$result\",\n")
       
      cat $xml_file | egrep -oE ''(<LINE>[^<]*</LINE>|<TEXT>[^<]*</TEXT>)'' | sed -e ''s:<LINE>::g'' -e ''s:</LINE>::g'' -e ''s:<TEXT>::g'' -e ''s:</TEXT>::g'' |sed ''$!N;s/\n/;/'' |while read linedata
      do
         if [ "$linedata" != "" ]
         then
         TEXT=$(echo $linedata |awk -F ";" ''{print $1}'')
         LINE=$(echo $linedata |awk -F ";" ''{print $2}'')
         if [ $item -ne $count ]
         then
           echo -e "\n\t\"issues$count\": {\n\t\t\"line\": \"$LINE\",\n\t\t \"text\": \"$TEXT\"\n},">>test.json
         else
          echo -e "\n\t\"issues$count\": {\n\t\t\"line\": \"$LINE\",\n\t\t \"text\": \"$TEXT\"\n}\n}\n" >>test.json
          sed -i ''1i ''"$(echo $json_header)"  $(System.DefaultWorkingDirectory)/target/test.json
         fi
         count=`expr $count + 1`
         fi
      done'