# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
      rootFolderOrFile: "$(Build.Repository.LocalPath)"
      includeRootFolder: false
      archiveFile: "$(Build.Repository.LocalPath)"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/helloworld.war'
  name: 'drop'

# - task: CmdLine@2
#   inputs:
#     script: 'curl -X POST   ''http://appsvr4.industrysoln.sl.edst.ibm.com:8004/sap/bc/srt/rfc/sap/zvsts_ci_check/350/zvsts_ci_check1/zvsts_ci_check1''   -H ''authorization: Basic YmNoYXR0ZXJqZWU6aWJtMTIz''   -H ''cache-control: no-cache''   -H ''content-type: text/xml''   -d ''<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:sap-com:document:sap:rfc:functions">
#    <soapenv:Header/>
#    <soapenv:Body>
#       <urn:ZVSTS_CI_CHECK>
#          <!--Optional:-->
#          <IM_I_EMAIL>
#             <!--Zero or more repetitions:-->
#             <item></item>
#          </IM_I_EMAIL>
#          <!--Optional:-->
#          <IM_V_OBJECT>ZMMR_MD05_SHORTAGE_REPORT</IM_V_OBJECT>
#          <!--Optional:-->
#          <IM_V_TRANSPORT></IM_V_TRANSPORT>
#       </urn:ZVSTS_CI_CHECK>
#    </soapenv:Body>
# </soapenv:Envelope>'''
- task: CmdLine@2
  inputs:
    script: 'curl -X POST   ''http://appsvr4.industrysoln.sl.edst.ibm.com:8004/sap/bc/srt/rfc/sap/zvsts_ci_check/350/zvsts_ci_check1/zvsts_ci_check1''   -H ''authorization: Basic YmNoYXR0ZXJqZWU6aWJtMTIz''   -H ''cache-control: no-cache''   -H ''content-type: text/xml''   -d ''<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:sap-com:document:sap:rfc:functions">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:ZVSTS_CI_CHECK>
         <!--Optional:-->
         <IM_I_EMAIL>
            <!--Zero or more repetitions:-->
            <item></item>
         </IM_I_EMAIL>
         <!--Optional:-->
         <IM_V_OBJECT>ZMMR_MD05_SHORTAGE_REPORT</IM_V_OBJECT>
         <!--Optional:-->
         <IM_V_TRANSPORT></IM_V_TRANSPORT>
      </urn:ZVSTS_CI_CHECK>
   </soapenv:Body>
</soapenv:Envelope>''>''$(System.DefaultWorkingDirectory)/target/sapp.xml'''

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/sapp.xml'
  